import{a as q,S as E,i as a}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const P="53514626-0b1a9606e501b3bd45a679ad3",R="https://pixabay.com/api/";async function m(s,r){const n=r??1;try{return(await q.get(R,{params:{key:P,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:15}})).data}catch(t){console.error("Error",t)}}const g=document.querySelector(".gallery"),y=document.querySelector(".loader"),h=document.querySelector(".load-more"),S=new E(".gallery a",{captionsData:"alt",captionDelay:250,captions:!1});function b(s){const r=s.map(e=>`<li class="gallery-item">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${e.likes}</p>
          <p><b>Views:</b> ${e.views}</p>
          <p><b>Comments:</b> ${e.comments}</p>
          <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </li>`).join("");g.insertAdjacentHTML("beforeend",r),S.refresh()}function $(){g.innerHTML=""}function L(){y.classList.add("visible")}function v(){y.classList.remove("visible")}function M(){h.classList.add("visible")}function c(){h.classList.remove("visible")}const p=document.querySelector("#form"),w=document.querySelector("#input"),O=document.querySelector(".load-more");let d="",i=1;const l=15;let f=0;c();p.addEventListener("submit",async s=>{s.preventDefault();const r=w.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a query",position:"topRight"});return}$(),c(),d=r,i=1,L();try{const e=await m(d,i,l);if(!e.hits||e.hits.length===0){a.info({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}f=e.totalHits,b(e.hits),i*l<f?M():(c(),a.info({title:"END",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){console.error("Error fetching images:",e),a.error({message:"Failed to fetch images. Please try again later.",position:"topRight"})}finally{v(),p.reset()}});O.addEventListener("click",async()=>{i+=1,L();try{const s=await m(d,i,l);b(s.hits);const r=document.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}i*l>=f&&(c(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){console.error("Error fetching more images:",s),a.error({title:"Error",message:"Failed to fetch more images. Please try again later.",position:"topRight"})}finally{v()}});console.log(w);
//# sourceMappingURL=index.js.map
